Document: otserv
Title: Debian otserv Manual
Author: <insert document author here>
Abstract: This manual describes what otserv is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/otserv/otserv.sgml.gz

Format: postscript
Files: /usr/share/doc/otserv/otserv.ps.gz

Format: text
Files: /usr/share/doc/otserv/otserv.text.gz

Format: HTML
Index: /usr/share/doc/otserv/html/index.html
Files: /usr/share/doc/otserv/html/*.html
